language: node_js
node_js:
- '4'
sudo: false
install:
- npm install -g serverless
- npm install
script:
- npm test
env:
  global:
  - secure: YiIrKIZdqI+mOCFK0OcpP2tOISwn8CpmZsnbkGqQxxEEYZeGGJTqoyj7NaG8DWOGub2pkac2ZR7XNY0T+ifswhC9z1knEmb9ZChpJD/5pi56Vfwihgep/mDJzWO2/DZ/A7dOxPCzXEDK5+ndZ/EJqAF7DoD9YWQsyWojL8tT9FjL43MH6ldlvmW9BnSyd/Ho+7oYcQtd++g9ztMQOWyLGMvS9NS/ADN50lq+xQDwz01feBIA9Z28FosQhkImp2TPSSy/RvOEXIKWyanJiJxZKbKgP63OXxoadQNrXXDaOBs5ep6zGSr0Sc3jEdoLdxOtoSYMYYHCm4vMMrnQkSk2ve6EDhPZbg0EZWeiF6MnP/qhm3PpVish20peZYo+CukybSTpd9+woxeguk9gl6l1+rItDaHN9E5HAISskXJvRI431KF5j7WUy9gclhGUaNIshb4Hc+RDZT8RFpubomRONxHEL37rq6OCqi7ikntrGjYr0h+YZinAJLB3U9jvOSCJamsMkS8x3lpamO0ceccSQgs49spBxBPctThXnZ7Pw7xVf2ea8E3GBZqhVY6prpG4VQ1YzmmRvMzLzdvy8RnhneZt9lJnME/Nq57GCiOdkAT/Ul1ZG2Vd/YNGEwVwnA5f4oVbjHYM36zD8oY6lf6ezuNDZ18K8sjeL0NU30e7AeY=
  - secure: mC05oH359VcHDfACwmIBb4nuzvwgwGwdlNrKpY2VS7yP8ol7lxTtGKXyO7B/IbaBWAXrCE8aAFRCNx+Ob2bUiw+/JgxZXBS6lJZhMIxF6uGdxQYrsiPqG17gJBICZ6milGtFaijUTUcLh7IcDynXaRGOMaixPsIRTwIG7CiTEh0m398F4U2F4YnbfIq98Yt1BqaiDlVJB4wO9F9CnmpAgdxptbmQrhlKd5/lClxPrelnpUb4D2hC4lYBLMgJvwQAwBkTLg1TCv58QrJMjqvQMAUnkdsHtkwOdycANB6q/Xo/QvSMiCb4CAPmZEunX6ik2c2F2Iy6dyedboZ1QzzR7z5GcBHqiLIKunlmzhKtD77imNUq4F+dsOHz1OtDap2SjfmaG8jxpSpkcWDMCj7ChG7iYcNq3L76ugMTRgdLT1Id4F9myvls5RcXkwJKTZN9YP49Yw/KZ6cNw3tF3xAtiQg0biysnU99Erz0kEDMiCEOCY8iWjw3xWdKHB3LcT56paafrZWCTM1CoIcs2iv4YpUy2SpFW/rdMXcP8na56lJoSU7zj572hAKkvdNnyNJ7LQ/wguZSI6+a6Z57SCmL62lp695mHJ9jSocG+jsd3itFya2n0hA6fhbObsMqbfxLFJPmGa2g3wkJl1wvgb1njVXgX0JfxUrQ4TYP9VlYKqY=
