language: node_js
node_js:
- '4'
sudo: false
install:
- npm install -g serverless
- npm install
script:
- npm test
env:
  global:
  - secure: ioycGsnC2qIXKr/cZU2nkcjmrY5Vejqs66jpkU6RC9z82T9WZRRg2zrRtU7VqYG6u5lyM3cPc39z+FELlHo3vNYmqzjPi+mqTcvFlkolUhCMML5RwLj86Izys3cAWlYKFLfrleWHFGyX/tmRq1dSlL07uo113t2GpJf0XRiMUv6X6zZxsMiyLTqK/Uu9HqXzNgtaLogYVx2f3wdTYClmGglDeKkUUU40c8+sPkCwIWVuPVbht9DCLYDBkEkWfEwWkwzQ4KPd4EbdCLuz2hK8bBlMw0O+0nioWqazyshavx5/PzWe9dd3K+lkB4x1kLnFlAvgNd9sX5A3JSjDMPsVfrAK0yYPpqDFLkw3HbgeKGCW3jOxKofAndVNZsokH/HC7Z2IojgIrYU7S/EGmNOHfAG9z3CA/PS+/6+fZ+3y5TPvNccK3bhL5JF5elI8hK0uL6NqVxbO/Ibc3RdbHzBCh1GpQ/p2KXnwySlOuQfjsIGHX1nGAaAFXcDVvbfhmArNbZmo4PfG8K9l+1cJsWkDnHF87Ba1IG5Qat6co/gvcuZZ9huWibVIBpB5pGtMgWROfkDzw8hFO5P2NxRYTNVZCR0E3ONzcwvXjIT8yN6Dag5K2sVvmsttMFlWBYr5ysV7Ma/eq47nZVe23KEOTyg8wWT56ErVt07kJg61lDFnWgA=
  - secure: YuMX55VBAMRNzquWKrZ5gIrJg2ypKogeLfWj6bzjYDThhgXEzT0o/ZArxQ3ljsMjPmlOoecEgdJLgmIYFJEx5X/Rh7QEt3zHGdtofixVLhBDoqzghqvvrAN+TA0q3Oq+V/8dTk9WSVEYiWic29MSRSO0jartV+5Bqi8j4LKDjNRl+ycK6XrLoRyy5ridGmUQ+cFMELHckqpVpZeYS8+jTsP886pW/6F3bckAFUuA8w95Wj1tuLjNT2rygbfegelKNN8BcjlU+M8uhnXL2lLOjeiBUR9JuiAY0HjtoQW1fP8naSjy5sAWpfV2yDXkDOaKt1KvbKE5d1COgtorcNSa93m95awKmSnYIrntLysyQrBT5I/lxM0qNu+u9rG6XQQpNEdb6ZbZ+Tzzl3C82DX+aY63r973dC5Hi7dj5rzorrimWHiZuoFystVjnaeDrFLGFqr6w01kr2FWO2RbbmwpUuPwjADYLFQSzyJHTtsTyYY2xMy/+5VttU/jxZt5uJcec59qfV3JWb8+ULPSCNJL9/VwjqePf665lNQw0pQr3G+1QISYRwGKV1BSJi+lVkc5VK9UdY5BvLkV+ua1khXesA/I/ea+lnabpazV0kEaagHcEAC9ohnFbOL3rTdCLZl7R3oD7HfUV3D6d6Th+LUu5PuFRIGoBMnzzHcENeKQ93A=
